In [3]:
pip install pandas


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import pandas as pd

In [5]:
s = pd.Series([1,2,3,4])
s

0    1
1    2
2    3
3    4
dtype: int64

In [6]:
s = pd.Series([1,2,3,4], index=['a','b','c','d'])
s

a    1
b    2
c    3
d    4
dtype: int64

In [7]:
data_dic = {'id':[1,2,3,4],
            'salary':[444,555,666,444],
            'dept':['abc','def','ghi','xyz']}
df_1 = pd.DataFrame(data_dic)
df_1

,id,salary,dept
0,1,444,abc
1,2,555,def
2,3,666,ghi
3,4,444,xyz


In [8]:
data = [[1,444,'abc'],
        [2,555,'def'],
        [3,666,'ghi'],
        [4,444,'xyz']
]
df = pd.DataFrame(data, columns=['id','salary','dept'])
display(df)
x = df.columns
index = ['R1','R2','R3','R4']
df.index = index
df

,id,salary,dept
0,1,444,abc
1,2,555,def
2,3,666,ghi
3,4,444,xyz


,id,salary,dept
R1,1,444,abc
R2,2,555,def
R3,3,666,ghi
R4,4,444,xyz


In [9]:
df.dtypes

id        int64
salary    int64
dept        str
dtype: object

In [10]:
def chk(df, ty):
    return df[ty].dtype

In [11]:
df['id'].dtype

dtype('int64')

In [12]:
df['dept'] = df['dept'].astype('category')


In [13]:
df.dtypes

id           int64
salary       int64
dept      category
dtype: object

In [14]:
df.tail(2)

,id,salary,dept
R3,3,666,ghi
R4,4,444,xyz


In [15]:
df.describe(include='category')

,dept
count,4
unique,4
top,abc
freq,1


In [16]:
df.index

Index(['R1', 'R2', 'R3', 'R4'], dtype='str')

In [17]:
df.columns

Index(['id', 'salary', 'dept'], dtype='str')

In [18]:
df['salary'].unique()

array([444, 555, 666])

In [19]:
df['salary'].nunique()

3

In [20]:
df['salary'].max()

np.int64(666)

In [21]:
df['salary'].min()

np.int64(444)

In [22]:
df['salary'].idxmax()

'R3'

In [23]:
df.info()

<class 'pandas.DataFrame'>
Index: 4 entries, R1 to R4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   id      4 non-null      int64   
 1   salary  4 non-null      int64   
 2   dept    4 non-null      category
dtypes: category(1), int64(2)
memory usage: 304.0+ bytes


In [24]:
df['salary'].sum()

np.int64(2109)

In [25]:
df['salary'].values

array([444, 555, 666, 444])

In [26]:
df.values

array([[1, 444, 'abc'],
       [2, 555, 'def'],
       [3, 666, 'ghi'],
       [4, 444, 'xyz']], dtype=object)

In [27]:
df.replace(555, 'Ali')

,id,salary,dept
R1,1,444,abc
R2,2,Ali,def
R3,3,666,ghi
R4,4,444,xyz


In [28]:
df.replace({444:"Ali", "abc":555})

TypeError: Cannot setitem on a Categorical with a new category (555), set the categories first

In [ ]:
x = df['salary'].iloc[3]
df.replace(x, 9000)

,id,salary,dept
R1,1,9000,abc
R2,2,555,def
R3,3,666,ghi
R4,4,9000,xyz


In [ ]:
df.iloc[2,1]

666

In [ ]:
df['salary'].iloc[0:2]

R1    444
R2    555
Name: salary, dtype: int64

In [ ]:
df.iloc[:, :-1]

,id,salary
R1,1,444
R2,2,555
R3,3,666
R4,4,444


In [ ]:
null = df.isnull().sum()

In [ ]:
null

id        0
salary    0
dept      0
dtype: int64

In [ ]:
import numpy as np
data = [[1,444,'abc'],
        [np.NAN,555,'def'],
        [3,666,'ghi'],
        [4,np.NAN,'xyz']
]
df = pd.DataFrame(data, columns=['id','salary','dept'])
df

,id,salary,dept
0,1.0,444.0,abc
1,NaN,555.0,def
2,3.0,666.0,ghi
3,4.0,NaN,xyz


In [ ]:
null = df.isnull().sum()
pd.DataFrame(null).T

,id,salary,dept
0,1,1,0


In [39]:
df.dropna(axis="column")

ValueError: No axis named column for object type DataFrame

In [37]:
df

,id,salary,dept
R1,1,444,abc
R2,2,555,def
R3,3,666,ghi
R4,4,444,xyz


In [ ]:
df.drop(['salary'],axis= 1)

KeyError: "['salary'] not found in axis"

In [ ]:
mean = df['salary'].mean()

In [ ]:
df['salary'] = df['salary'].fillna(value=mean)


In [ ]:
df

,id,salary,dept
0,1.0,444.0,abc
1,NaN,555.0,def
2,3.0,666.0,ghi
3,4.0,555.0,xyz


In [ ]:
Header_col = ['index','gender','dept','postal_code']
data=pd.read_table('http://bit.ly/movieusers',sep='|',header=None, names= Header_col)
data

,index,gender,dept,postal_code
1,24,M,technician,85711
2,53,F,other,94043
3,23,M,writer,32067
4,24,M,technician,43537
5,33,F,other,15213
...,...,...,...,...
939,26,F,student,33319
940,32,M,administrator,02215
941,20,M,student,97229
942,48,F,librarian,78209


In [ ]:
user_info=pd.read_csv('http://bit.ly/uforeports')

In [ ]:
user_info.head()

,City,Colors Reported,Shape Reported,State,Time
0,Ithaca,NaN,TRIANGLE,NY,6/1/1930 22:00
1,Willingboro,NaN,OTHER,NJ,6/30/1930 20:00
2,Holyoke,NaN,OVAL,CO,2/15/1931 14:00
3,Abilene,NaN,DISK,KS,6/1/1931 13:00
4,New York Worlds Fair,NaN,LIGHT,NY,4/18/1933 19:00


In [ ]:
user_info.shape

(18241, 5)

In [ ]:
user_info['Location'] = user_info.City + ' ' + user_info.State
user_info.head()

,City,Colors Reported,Shape Reported,State,Time,Location
0,Ithaca,NaN,TRIANGLE,NY,6/1/1930 22:00,Ithaca NY
1,Willingboro,NaN,OTHER,NJ,6/30/1930 20:00,Willingboro NJ
2,Holyoke,NaN,OVAL,CO,2/15/1931 14:00,Holyoke CO
3,Abilene,NaN,DISK,KS,6/1/1931 13:00,Abilene KS
4,New York Worlds Fair,NaN,LIGHT,NY,4/18/1933 19:00,New York Worlds Fair NY


In [ ]:
user_info.to_csv('test.csv')

In [ ]:
user_info.rename(columns={'Colors Reported':'Colors_Reported'})

,City,Colors_Reported,Shape Reported,State,Time,Location
0,Ithaca,NaN,TRIANGLE,NY,6/1/1930 22:00,Ithaca NY
1,Willingboro,NaN,OTHER,NJ,6/30/1930 20:00,Willingboro NJ
2,Holyoke,NaN,OVAL,CO,2/15/1931 14:00,Holyoke CO
3,Abilene,NaN,DISK,KS,6/1/1931 13:00,Abilene KS
4,New York Worlds Fair,NaN,LIGHT,NY,4/18/1933 19:00,New York Worlds Fair NY
...,...,...,...,...,...,...
18236,Grant Park,NaN,TRIANGLE,IL,12/31/2000 23:00,Grant Park IL
18237,Spirit Lake,NaN,DISK,IA,12/31/2000 23:00,Spirit Lake IA
18238,Eagle River,NaN,NaN,WI,12/31/2000 23:45,Eagle River WI
18239,Eagle River,RED,LIGHT,WI,12/31/2000 23:45,Eagle River WI


In [ ]:
user_info.columns = user_info.columns.str.replace(' ', '_')
user_info.head()

,City,Colors_Reported,Shape_Reported,State,Time,Location
0,Ithaca,NaN,TRIANGLE,NY,6/1/1930 22:00,Ithaca NY
1,Willingboro,NaN,OTHER,NJ,6/30/1930 20:00,Willingboro NJ
2,Holyoke,NaN,OVAL,CO,2/15/1931 14:00,Holyoke CO
3,Abilene,NaN,DISK,KS,6/1/1931 13:00,Abilene KS
4,New York Worlds Fair,NaN,LIGHT,NY,4/18/1933 19:00,New York Worlds Fair NY
